const ExperienceData = [
  {
    id: 1,
    jobtitle: "Head of Department",
    companyname: "Social Boost",
    worktype: "Full-time",
    duration: "Jan 2021 - Oct 2021",
    location: "Tbilisi, Georgia",
    responsibility: [
      `Ensuring the team conduct bespoke campaigns based on client’s requirements to ensure client satisfaction.`,
      `Ensure all company marketing practices are followed by the team correctly.`,
      `Create, develop and test new growth strategies to improve results for company clients.`,
      `Ensuring that retention rate targets are met by the team.`,
      `Managing training syllabus for new recruits & holding trainings personally.`,
      `Ensure the team acknowledge and act to resolve all client complaints.`,
      `Report team performance each week to company Director.`,
      `Keep written records of individual team member performance and record errors.`,
      `Hold regular meetings and performance reviews with team leaders.`,
    ],
  },
  {
    id: 2,
    jobtitle: "Team Lead",
    companyname: "Social Boost",
    worktype: "Full-time",
    duration: "Sep 2020 - Jan 2021",
    location: "Tbilisi, Georgia",
    responsibility: [
      `Leading a team of Instagram Growth Specialists in growing Instagram Accounts organically for businesses and influencers.`,
      `Working closely with Client Success Management team to ensure all client’s requirements are met.`,
      `Reporting performance to management.`,
      `Overseeing Organic Instagram growth campaigns.`,
      `Ensuring the highest levels of quality across the team.`,
    ],
  },
  {
    id: 3,
    jobtitle: "Instagram Growth Specialist",
    companyname: "Social Boost",
    worktype: "Full-time",
    duration: "Jul 2020 - Sep 2020",
    location: "Tbilisi, Georgia",
    responsibility: [
      `Hand-growing Instagram accounts manually via the Instagram app.`,
      `Interacting with people to generate highly engaged niche audiences.`,
      `Researching targets to ensure the highest quality Instagram growth is achieved.`,
      `Using organic Instagram growth techniques`,
      `Doing hashtag and competitor account research`,
      `Heling with audience and engagement building`,
    ],
  },
  {
    id: 4,
    jobtitle: "Sales Specialist",
    companyname: "Be-Canadian Immigration Agency",
    worktype: "Full-time",
    duration: "Jul 2019 - Feb 2020",
    location: "Tbilisi, Georgia",
    responsibility: [
      `Reaching out to customers interested in immigration to Canada via phone calls (warm calls).`,
      `Offering services using solid arguments and providing information on how immigration works.`,
      `Maintaining positive business/customer relationships.`,
      `Achieving monthly sales targets. `,
      `Providing management with reports of daily activity using the CRM system. `,
      `Writing custom e-mails to customers. `,
      `Using follow-up/callback strategies. `,
      `I also helped with hiring new people and providing them with training`,
    ],
  },
  {
    id: 5,
    jobtitle: "Chief Executive Officer",
    companyname: "Catrisa Lingerie",
    worktype: "Self-employed",
    duration: "2019 - 2020",
    location: "Tbilisi, Georgia",
    responsibility: [
      `Online lingerie store start-up catrisa.ge. I was managing all the aspects of the company on my own. Sales were done online/locally only. My first business failed and the biggest reason was Covid-19 as I was unable to fulfill the orders and refill the stock. Received a lot of experience in how retail business works and improved my skills with customer support, web development, local SEO as well as content and social media management.`,
    ],
  },
  {
    id: 6,
    jobtitle: "Promotion Agent",
    companyname: "Nightclubs / Bars and Restaurant",
    worktype: "Freelance",
    duration: "2017 - 2019",
    location: "Tbilisi, Georgia",
    responsibility: [
      `Approaching potential customers, giving presentations, distributing fliers, and promoting the services/idea to join specific bars/clubs.`,
      `I mostly worked with foreign customers in English, Russian, and sometimes German.`,
    ],
  },
  {
    id: 7,
    jobtitle: "Sales Specialist",
    companyname: "Next Brand",
    worktype: "Full-time",
    duration: "Jul 2015 - Jul 2017",
    location: "Tbilisi, Georgia",
    responsibility: [
      `Reaching out to existing/potential customers via phone calls including cold and warm calls.`,
      `Promoting/selling services using solid arguments.`,
      `Maintaining positive business/customer relationships.`,
      `Achieving monthly sales targets. `,
      `Providing management with reports of daily activity using the CRM system. `,
      `Writing custom e-mails to customers. `,
      `Using follow-up/callback strategies. `,
    ],
  },
  {
    id: 8,
    jobtitle: "Child Care Specialist",
    companyname: "Au Pair",
    worktype: "Full-time",
    duration: "Jul 2014 - Jul 2015",
    location: "Breisach am Rhein, Baden-Württemberg, Germany",
    responsibility: [
      `Taking host child to kindergarten. `,
      `Playing, reading, or walking outside with the host child. `,
      `Cooking food and cleaning the room for the host child, including minor household duties.`,
    ],
  },
  {
    id: 9,
    jobtitle: "Waitress",
    companyname: "Club IVERIA",
    worktype: "Full-time",
    duration: "Jul 2012 - Jul 2014",
    location: "Tbilisi, Georgia",
    responsibility: [
      `Providing customer service. `,
      `Greeting customers and taking food/drink orders. `,
      `Making suggestions based on their preference.`,
      `Keeping ashtrays clean and tables tidy. `,
      `Cooperating between customers and the serving staff. `,
    ],
  },
];

const EducationData = [
  {
    name: "Tbilisi State University",
    status: "Ba, Psychology",
    year: "2012 - 2014",
  },
  {
    name: "Tbilisi public school N154",
    status: "",
    year: "2000 - 2012",
  },
];

export { ExperienceData, EducationData };
